### ISSUE TITLE
Wall issues

### ISSUE THREAD

**Issue by skskwn** [Mirroar/hivemind#8]
In RCL 3, Creeps does not upgrade the walls.

**Comment by Mirroar** [comment]
Well, kind of. Only in your first room, ramparts are built as early as RCL 3, on later expansions they are only built starting at RCL 4. When at RCL 3, repairing ramparts is not a priority for builder creeps (because it's much more important to get other buildings up and get the controller to level 4 quickly). See [this line](https://github.com/Mirroar/hivemind/blob/9181567026673645adf0d06dcb3d7ba13efc05fa/src/role.builder.js#L257).

**Comment by skskwn** [comment]
I'm growing up in the first room. However, the upgrade creeps only occurs when the wall is close to the downgrade. Therefore, the controller level does not rise rapidly. Also, when the walls are broken and disappeared without upgrading, construction is done over and again. Is this normal?
